### ISSUE TITLE
Creating tagged VLAN interfaces which could be used for MachineNetwork

### ISSUE THREAD

**Issue by linusali** [karmab/aicli#12]
This could be an RFE, but could we include creating VLAN interfaces as part of `static_network_config`. I have tried it myself as a workaround with  VLAN interface name starting with "bond" and omitting mac address param. I had to also add the parent interface with ipv4 set to disabled.

Probably in the following line we could add "vlan" or "." as part of the "if" statement. 
https://github.com/karmab/assisted-installer-cli/blob/48fdcc7c693b55f454ea3f4765fb3f26f2e1cb59/ailib/__init__.py#L243

**Comment by karmab** [comment]
addressed in https://github.com/karmab/aicli/commit/47a26d24139eb55e722f3ad72efcc29fb391ff39 
sorry for the stupid delay!
