### ISSUE TITLE
Support for ListCluster filters

### ISSUE THREAD

**Issue by avishayt** [karmab/aicli#23]
It would be great if aicli could support passing the `openshift_cluster_id` and `ams_subscription_ids` filters to ListClusters.  This would help cases where we have one of those IDs but not the Assisted ID.  Thanks!

**Comment by karmab** [comment]
addressed in https://github.com/karmab/aicli/commit/529a94c9c8335e982961c465bbf3ef42120f38f4
you can run something like

```
aicli list cluster -f ams_subscription_id=xxx
aicli list cluster -f org_id=yyy
aicli list cluster -f ams_subscription_id=xxx,org_id=yyy
```

**Comment by karmab** [comment]
simplified the approach in https://github.com/karmab/aicli/commit/18848100cf85a52ae4db7ba36aba7e10fd5366fa
so that you can instead do

```

aicli list cluster -s xxx
aicli list cluster -o yyy
```
