### ISSUE TITLE
Cannot recreate OCP cluster after deleting it with aicli

### ISSUE THREAD

**Issue by ernes11t0** [karmab/aicli#27]
Hello,

I created an OCP cluster using aicli, it worked perfect. 

I need to do the installation again due to some misconfiguration. 

I deleted the cluster executing:

`aicli delete cluster my-cluster`

Then, I deleted the aicli image from podman and recreated it: 

```
podman rmi quay.io/karmab/aicli:latest 

alias aicli='podman run --rm -e AI_OFFLINETOKEN=${TOKEN} -v ${HOME}/.ssh/:/root/.ssh/:Z -v $HOME/.aicli:/root/.aicli:Z -v ${HOME}/.aicli/:/workdir:Z quay.io/karmab/aicli:latest'
```

I just exported my token and created the file aicli-parameters.yaml and OpenShift pull secret (as I did the first time I installed the cluster).

Now, when I try to create the new cluster, the command stops the executions with no returns (Creating cluster message was expected) 

```
[my-user@my-bastion .aicli]$ aicli create cluster --paramfile aicli-parameters.yaml my-cluster
[my-user@ my-bastion .aicli]$ aicli list clusters
Removing old offlinetoken file
+---------+----+--------+------------+
| Cluster | Id | Status | Dns Domain |
+---------+----+--------+------------+
+---------+----+--------+------------+
[my-user@ my-bastion .aicli]$ aicli list infraenv
+----------+----+---------+-------------------+----------+
| Infraenv | Id | Cluster | Openshift Version | Iso Type |
+----------+----+---------+-------------------+----------+
+----------+----+---------+-------------------+----------+
```
Do you know why I am not able to recreate the cluster once it is deleted? 

I need to say also that the cluster I first created is still working and it is a one node cluster. 

Any help on this issue will be extremely appreciated. 

Best regards.

**Comment by karmab** [comment]
this is a surprising behaviour, if AI was preventing the same cluster to be created again, i believe you would at least get an answer from the service.
Does creating a brand new cluster work at the moment?
