### ISSUE TITLE
Fetching the Cluster Logs (View Cluster Logs) during the progress of the Installation

### ISSUE THREAD

**Issue by vu3oim** [karmab/aicli#29]
Is there support in aicli to view the cluster events in "realtime" when the installation is started?
In the AI GUI, there is the button 'View Cluster Events', that shows the ongoing progress. We are checking if such a function is there already via aicli?

**Comment by karmab** [comment]
yes, you can do 

````
aicli get events $cluster -f
```

**Comment by vu3oim** [comment]
Thanks.
