### ISSUE TITLE
TLS (https) support in aicli to talk to AI Services over https

### ISSUE THREAD

**Issue by vu3oim** [karmab/aicli#31]
Does aicli support https protocol when talking to AI Services?
If it does support, any documentation about it?

**Comment by karmab** [comment]
does AI api support it?

**Comment by vu3oim** [comment]
Yes, as I know its supported.

The following variables must be set to enable TLS:
•	HTTPS_KEY_FILE - tls key file path
•	HTTPS_CERT_FILE - tls cert file path
•	ASSISTED_SERVICE_SCHEME - protocol to use to query assisted service for image information (https)

Reference: https://github.com/openshift/assisted-image-service/blob/main/README.md

**Comment by vu3oim** [comment]
Any help here?

**Comment by karmab** [comment]
addressed in https://github.com/karmab/aicli/commit/4ce1a2d58919734278ed65478597045b10f8739f
with the correspondin doc at https://aicli.readthedocs.io/en/latest/#tls-settings

**Comment by vu3oim** [comment]
Thanks for this, but I had a question.

Without this change what you have done, earlier also aicli was supporting https URLs (towards Assisted Service). 
That is, we have hosted our AI Services on 443 (https) and we were able to use the aicli command very well towards that end point (over TLS). Our AI Services run with our custom CA signed certs. Also, note that we did not have the CA cert into the Linux OS Trust bundle too. Still aicli worked successfully.

So, now I wonder why this correction is needed, where it helps?
Can you highlight me please?

Just to say again: without this correction, we are still able to use aicli to talk to our offline AI Services hosted in TLS mode.
