### ISSUE TITLE
Cluster creation fails with "Setting Machine network CIDR is forbidden when cluster is not in vip-dhcp-allocation mode"

### ISSUE THREAD

**Issue by vu3oim** [karmab/aicli#35]
We are trying to install using Assisted Installer offline, OCP 4.10.26 cluster with 'pure IPv4' network (no dual stack) and the following command always fails =>

aicli --url=http://localhost:8090/ create cluster test --paramfile /var/cluster_parameters.yaml

Creating cluster test 
Traceback (most recent call last):
  File "/home/admin/.local/bin/aicli", line 11, in <module>
    sys.exit(cli())
  File "/home/admin/.local/lib/python3.6/site-packages/ailib/cli.py", line 1229, in cli
    args.func(args)
  File "/home/admin/.local/lib/python3.6/site-packages/ailib/cli.py", line 69, in create_cluster
    ai.create_cluster(args.cluster, overrides.copy())
  File "/home/admin/.local/lib/python3.6/site-packages/ailib/__init__.py", line 410, in create_cluster
    self.update_cluster(name, extra_overrides)
  File "/home/admin/.local/lib/python3.6/site-packages/ailib/__init__.py", line 878, in update_cluster
    self.client.v2_update_cluster(cluster_id=cluster_id, cluster_update_params=cluster_update_params)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api/installer_api.py", line 4982, in v2_update_cluster
    (data) = self.v2_update_cluster_with_http_info(cluster_id, cluster_update_params, **kwargs)  # noqa: E501
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api/installer_api.py", line 5067, in v2_update_cluster_with_http_info
    collection_formats=collection_formats)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 389, in request
    body=body)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/rest.py", line 295, in PATCH
    body=body)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/rest.py", line 228, in request
    raise ApiException(http_resp=r)
assisted_service_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Fri, 09 Sep 2022 06:13:07 GMT', 'Content-Length': '150'})
HTTP response body: {"code":"400","href":"","id":400,"kind":"Error","reason":"Setting Machine network CIDR is forbidden when cluster is not in vip-dhcp-allocation mode"}

The input file cluster_parameters.yaml is as follows =>

pull_secret: /var/pull-secret-update.txt
additional_ntp_source: 10.18.17.40
high_availability_mode: Full
schedulable_masters: false
api_vip: 10.91.129.194
ingress_vip: 10.91.129.195
vip_dhcp_allocation: false
openshift_version: "4.10"
base_dns_domain: abc.com
ssh_public_key: "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmllzdHA1MjEAAACFBACW1MMoFAuG9msxyg/63b4mM5V1MAzTCefZ5Q9pc0nU7ZLds1KzJdoDzUSPI9XPziUgAQx2+6UgY5FFt30Q+SbEzAHoqvgFOcbjz2srEmg7aH+Np/ZuJQycGYzNlROztyDCxAm2qoFDnoE2KKMzzaSMsi0RNyurFzZxpINDOQ== admin@test"
network_type: OVNKubernetes

machine_networks:
- cidr: 10.91.128.0/20
service_networks:
- 172.30.0.0/16
cluster_networks:
- cidr: 10.128.0.0/14
   hostPrefix: 23

installconfig:
  platform:
    baremetal:
      clusterosimage: http://myimgsrv:8080/rhcos-4.10.16-x86_64-openstack.x86_64.qcow2.gz?sha256=e0a1d8a99c5869150a56b8de475ea7952ca2fa3aacad7ca48533d1176df503ab
ignition_config_override: '{"ignition": {"version":"3.2.0"},"storage": {"files": [{"path": "/etc/pki/ca-trust/source/anchors/reg_ca.pem","mode": 420,"overwrite": true,"user": {"name": "root"},"contents": {"source": "data:text/plain;base64,<...>="}},{"contents": {"source": "data:text/plain;charset=utf-8;base64,ZGVmYXVsdHMgewogICAgdXNlcl9mcmllbmRseV9uYW1lcyB5ZXMKICAgIGZpbmRfbXVsdGlwYXRocyB5ZXMKICAgIGVuYWJsZV9mb3JlaWduICJeJCIKfQpibGFja2xpc3RfZXhjZXB0aW9ucyB7CiAgICBwcm9wZXJ0eSAiKFNDU0lfSURFTlRffElEX1dXTikiCn0KYmxhY2tsaXN0IHsKfQo="},"filesystem": "root","mode": 420,"path" :"/etc/multipath.conf"}]},"systemd": {"units": [{"name": "multipathd.service","enabled": true}]}}'

fips: true

If you see in the above yaml, the machine_networks is specified. This leads to =>
"Setting Machine network CIDR is forbidden when cluster is not in vip-dhcp-allocation mode"

I have attached the tcpdump network capture showing the final PATCH command failing.

But when we remove the machine_networks entry (with its cidr) from the file, the cluster creation is successful.

Question: machine_networks is necessary or not necessary to be specified?

Additional Information: We then created the same cluster using JSON file and using curl command to fire it to the AI Service. This JSON has the machine_networks entry and the cluster created successfully. JSON used here (cluster_configv4.json) =>

{
    "additional_ntp_source": "10.18.17.40",
    "name": "test",
    "high_availability_mode": "Full",
    "schedulable_masters": true,
    "api_vip": "10.92.82.170",
    "ingress_vip": "10.92.82.171",
    "vip_dhcp_allocation": false,
    "openshift_version": "4.10",
    "base_dns_domain": "netact.nsn-rdnet.net",
    "pull_secret": "{\"auths\": {\"test.com:5000\": {\"auth\": \"cmVyMw==\"}}}",
    "ssh_public_key": "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAEyCQqywxcBhNuAuYoYGt+ktrzcNQ+PSZ+qnL/wrKJiXeXIQTLWyfyLT0G/HjhbINtTpnmSkAiiSB5FHRzx262KKQFag92QFUHTpmAmgNUs3SID1Xu3hzHkdKhBXLnA== admin@test",
    "network_type": "OVNKubernetes",
    "machine_networks": [
      {
        "cidr": "10.92.80.0/20"
      }
    ],
    "service_networks": [
      {
        "cidr": "172.30.0.0/16"
      }
    ],
    "cluster_networks": [
      {
        "cidr": "10.128.0.0/14",
        "host_prefix": 23
      }
    ]
}

Then doing =>

curl -H "Content-Type: application/json" -d @/var/tmp/cluster_configv4.json -X POST http://localhost:8090/api/assisted-install/v2/clusters

WORKS OK!

What could be going wrong here?

**Comment by vu3oim** [comment]
[tcpdump.txt](https://github.com/karmab/aicli/files/9534918/tcpdump.txt)

**Comment by vu3oim** [comment]
I would like to give an update here..

For pure IPv4 based installation, we have been told that we must NOT specify the machine_networks.
So, we have remove the following in our cluster_parameters.yaml and the cluster creation + installation works OK.

"machine_networks": [
{
"cidr": "10.92.80.0/20"
}

**Comment by karmab** [comment]
no bugs means i m closing!
