### ISSUE TITLE
How to specify during installation that FIPS has to be enabled

### ISSUE THREAD

**Issue by vu3oim** [karmab/aicli#37]
As per the AI interface definitions =>
https://raw.githubusercontent.com/openshift/assisted-service/master/swagger.yaml

following is said =>
install_config_overrides:
        x-go-custom-tag: gorm:"type:text"
        type: string
        description: JSON-formatted string containing the user overrides for the install-config.yaml file.
        example: '{"networking":{"networkType": "OVNKubernetes"},"fips":true}'

In our installations, we want to set fips=true.
How can this be set via aicli?

We tried with the following cluster_parameters.yaml while cluster creation, but FIPS is not getting enabled.

pull_secret: /home/pull-secret.txt
additional_ntp_source: 110.18.4.4
high_availability_mode: Full
schedulable_masters: true
api_vip: 100.193.65.196
ingress_vip: 100.193.65.197
vip_dhcp_allocation: false
openshift_version: "4.10"
base_dns_domain: dyn..net
ssh_public_key: "ecdsa-sha2-nistp521 AAAAE2VjZH"
network_type: OVNKubernetes

machine_networks:
 - cidr: 100.193.65.192/27
 - cidr: 5A00:8A00:4000:020c:0000:0000:0146:0000/112
service_networks:
 - 172.30.0.0/16
 - fd03::/112
cluster_networks:
 - cidr: 10.128.0.0/14
   hostPrefix: 23
 - cidr: fd02::/48
   hostPrefix: 64
installconfig:
  platform:
    none: {}
ignition_config_override: '{"ignition": {"version": "3.2.0"}, "storage": {"files":[{"path": "/etc/pki/ca-trust/source/anchors/reg_ca.pem", "mode": 420, "overwrite":true,"user": { "name": "root"},"contents": {"source": "data:text/plain;base64,xyz'
fips: true

**Comment by karmab** [comment]
added in https://github.com/karmab/aicli/commit/4d613b01678ce3cead3b1bf092aea03f5f7864ba
so that it's enough to set fips in your paramfile
Note that you could have used something like
install_config: '{"networking":{"networkType": "OVNKubernetes"},"fips":true}'

**Comment by vu3oim** [comment]
Thanks that helps.
