### ISSUE TITLE
Decrease "Waiting" message amount or move to debug only

### ISSUE THREAD

**Issue by krembu** [karmab/aicli#44]
Hi @karmab 

could you consider decreasing the amount of "Waiting" for host/cluster messages, maybe put them only when user run with debug
or single message "Waiting ${TIMEOUT}s for cluster to reach state installed"

https://github.com/karmab/aicli/blob/main/ailib/__init__.py#L960-L1001

**Comment by karmab** [comment]
addressed in https://github.com/karmab/aicli/commit/d2753cc7541d006a5d5947aaf69dfbc156103c69
