### ISSUE TITLE
Stream events while cluster is installing

### ISSUE THREAD

**Issue by rabin-io** [karmab/aicli#57]
Can you please add the option to monitor the `events` endpoint to monitor cluster installation?

At the moment with ABI installs I do this with `curl` and `jq`

```sh
curl \
  -H "Authorization: ${AI_TOKEN}" \
  -H "Content-Type: application/json"  \
  http://10.11.10.11:8090/api/assisted-install/v2/events | jq '.|last'
```

**Comment by karmab** [comment]
you can use aicli get events -f
