### ISSUE TITLE
[RFE] Support new network syntax in AI backend

### ISSUE THREAD

**Issue by mkowalski** [karmab/aicli#8]
## AI Backend Change

Some days ago [we have introduced a new syntax for setting networks in the AI backend](https://github.com/openshift/assisted-service/pull/2339). It changes the behaviour so that instead of currently used fields

* `machine_network_cidr`
* `cluster_network_cidr`
* `cluster_network_host_prefix`
* `service_network_cidr`

the following are used

* `machine_networks`
* `cluster_networks`
* `service_networks`

The syntax is shown in the example cURL request below

```
-H 'Content-Type: application/json' -X PATCH --data '{
  "cluster_networks":[{"cidr":"10.128.0.0/14","host_prefix":23}],
  "service_networks":[{"cidr":"172.30.0.0/16"}],
  "machine_networks":[{"cidr":"192.168.145.0/24"}]
}'
```

## Backwards Compatibility

Backwards compatibility is preserved.

### GET

Responses to `GET` requests contain both old and new fields organized in the following way

*  `{...}_network_cidr` contains the CIDR from the first entry from respective `{...}_networks`
*  `cluster_network_host_prefix` contains the host prefix from the first entry from `cluster_networks`

**Comment by karmab** [comment]
thanks for the heads up!

**Comment by karmab** [comment]
already handled in the code
